// assets
export const FETCHING_COIN_DATA = 'FETCHING_COIN_DATA';
export const FETCHING_COIN_DATA_SUCCESS = 'FETCHING_COIN_DATA_SUCCESS';
export const FETCHING_COIN_DATA_ERROR = 'FETCHING_COIN_DATA_ERROR';
// history
export const FETCHING_COIN_HISTORY = 'FETCHING_COIN_HISTORY';
export const FETCHING_COIN_HISTORY_SUCCESS = 'FETCHING_COIN_HISTORY_SUCCESS';
export const FETCHING_COIN_HISTORY_ERROR = 'FETCHING_COIN_HISTORY_ERROR';